import CartSidebar from "@/components/CartSideBar";
import "../globals.css";
import dynamic from "next/dynamic";
import { Roboto } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

const DynamicNavbar = dynamic(() => import("@/components/Navbar"), {
  ssr: false,
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="bg-white" lang="en">
      <body className={` ${roboto.className}`}>
        <div className="w-screen max-w-full overflow-hidden text-black">
          <DynamicNavbar />
          <div className="mt-16">{children}</div>
          <CartSidebar />
        </div>
      </body>
    </html>
  );
}
